### ISSUE TITLE
Windows10エディションでアプリ一覧を開けない

### ISSUE THREAD

**Issue by popkechupki** [CoSSeDevelopmentTeam/CPhone#6]
## エラー文
> 10:39:12 [FATAL] "CPhone v1.3.3"に"cn.nukkit.event.server.DataPacketReceiveEvent"Eventを渡すことができませんでした: net.comorevi.cphone.plugin.EventListenerでのnull
10:39:12 [ERROR] Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2093) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1507) ~[?:?]
	at cn.nukkit.network.Network.processPackets(Network.java:197) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.Network.processBatch(Network.java:180) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2099) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:83) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tick(Server.java:1132) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:911) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.start(Server.java:888) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:573) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) ~[nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
	at net.comorevi.cphone.cphone.ApplicationListActivity.lambda$init$0(ApplicationListActivity.java:46) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1507) ~[?:?]
	at net.comorevi.cphone.cphone.ApplicationListActivity.init(ApplicationListActivity.java:44) ~[?:?]
	at net.comorevi.cphone.cphone.ApplicationListActivity.onCreate(ApplicationListActivity.java:29) ~[?:?]
	at net.comorevi.cphone.cphone.widget.activity.ActivityBase.start(ActivityBase.java:61) ~[?:?]
	at net.comorevi.cphone.cphone.HomeActivity.onStop(HomeActivity.java:49) ~[?:?]
	at net.comorevi.cphone.presenter.ActivityProcessor.stop(ActivityProcessor.java:97) ~[?:?]
	at net.comorevi.cphone.plugin.EventListener.onDataPacket(EventListener.java:61) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
	... 16 more

## めも
最初言語が英語設定だったので日本語に変えてみましたが変わりませんでした。

**Comment by popkechupki** [comment]
Applications.dbの削除で解決しました。
